export const CREATE_MOVIE_REVIEW = "CREATE_MOVIE_REVIEW";
export const DELETE_MOVIE_REVIEW = "DELETE_MOVIE_REVIEW";
export const GET_ALL_MOVIE_REVIEW = "GET_ALL_MOVIE_REVIEW";
export const GET_MOVIE_REVIEW = "GET_MOVIE_REVIEW";
export const SEARCH_MOVIE_REVIEW = "SEARCH_MOVIE_REVIEW";
export const UPDATE_MOVIE_REVIEW = "UPDATE_MOVIE_REVIEW";

export const START_LOADING_MOVIE_REVIEW = "START_LOADING_MOVIE_REVIEW";
// export const REST_MOVIE_REVIEW_LIST = "REST_MOVIE_REVIEW_LIST";
