export const GET_CURRENT_MOVIE_COMMENTS = "GET_CURRENT_MOVIE_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
