export const CREATE_MOVIE_REVIEW = "CREATE_MOVIE_REVIEW";
export const DELETE_MOVIE_REVIEW = "DELETE_MOVIE_REVIEW";
export const GET_ALL_MOVIE_REVIEW = "GET_ALL_MOVIE_REVIEW";
export const GET_MOVIE_REVIEW = "GET_MOVIE_REVIEW";
