export const UPDATE_MOVIE_REVIEW_AFTER_ACTION_IN_ONE_RATE =
  "UPDATE_MOVIE_REVIEW_AFTER_ACTION_IN_ONE_RATE";
export const UPDATE_USER_MOVIE_RATES_USER = "UPDATE_USER_MOVIE_RATES_USER";

// export const DELETE_ONE_RATE = "DELETE_ONE_RATE";
